apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
data:
  application-dev.yaml: |
    server:
      port: {{ .Values.app.port }}
    app_id: {{ .Values.app_id }}
    secret: {{ .Values.secret }}